name: huggingface space

on:
  workflow_dispatch:
  schedule:
    - cron: "00 12 * * *"

jobs:
  google_search:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install required Python dependencies
      run: |
        pip install DrissionPage DataRecorder tqdm aiohttp pandas python-dotenv httpx cloudflare requests waybackpy cdx_toolkit bs4 lxml

    - name: Run the hg model count
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_D1_DATABASE_ID: ${{ secrets.CLOUDFLARE_D1_DATABASE_ID }}
      run: |
        # python hg-spaces.py
        python hg-models.py

    - name: Create date file
      run: |
        echo "$(date +'%Y-%m-%d %H:%M:%S')" > huggingface.txt

    - name: Commit the results to the repository
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
      
        git add -A
        git commit -m "Add new huggingface results and update date file"
        git push
